# Generated by Django 6.0.4 on 2026-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending ⏳'), ('Confirmed', 'Confirmed ✅'), ('Shipped', 'Shipped 🚚'), ('Delivered', 'Delivered 🎉'), ('Cancelled', 'Cancelled ❌')], default='Pending', max_length=20),
        ),
    ]
